all:
	gcc -g parser.c \
	utils.c \
	main.c \
	errors.c \
	linked_list.c \
	libft.c \
	add_arguments.c \
	check_chars.c \
	check_syntax.c \
	parse_out_quotes.c \
	env.c \
	env_vars.c \
	simple_quotes.c

test:
	gcc -g parser.c \
	utils.c \
	tester.c \
	errors.c \
	linked_list.c \
	libft.c \
	add_arguments.c \
	check_chars.c \
	check_syntax.c \
	parse_out_quotes.c \
	env.c \
	env_vars.c \
	simple_quotes.c